### ISSUE TITLE
The application is currently offline, refreshing the page will cause data loss

### ISSUE THREAD

**Issue by mickael-kerjean** [wekan/wekan#1113]
Hello,

Before everything, thank you for creating such an awesome piece of software. Wekan is really awesome.

I'm not sure if it's normal but everytime I reload the page, I get this screen:
![image](https://user-images.githubusercontent.com/13233076/27860095-697d8da0-61be-11e7-96f1-2c1aac932056.png)

After a few seconds the actual page show up but it feels a bit weird to me. 
Is it the normal behavior or maybe something is wrong with my configuration?
I'm using the docker version of wekan behind nginx and I got no errors coming from the developer console.

**Comment by xet7** [comment]
That error comes when Wekan is offline. If wekan really is online, just refresh page.

Did you use modified docker-compose.yml file to run Wekan?
https://github.com/wekan/wekan-mongodb

**Comment by mickael-kerjean** [comment]
Well that's the thing, wekan isn't offline. Everytime I refresh the page I receive the error and the page shows up a few seconds after.

The only difference with the official docker-compose file I updated the location of the mongodb files on the host machine.

**Comment by xet7** [comment]
On docker-compose file, did you set ROOT_URL to real wekan address on Nginx, for example https://example.com/wekan ?

**Comment by xet7** [comment]
and also port to localhost port to the port where Wekan is running on localhost ?

**Comment by mickael-kerjean** [comment]
I guess so. That's my docker-compose file:
```
version: '2'

services:
  wekandb:
    image: mongo:3.2.13
    restart: always
    container_name: app_wekan_db
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db

  wekan:
    image: wekanteam/wekan:latest
    restart: always
    container_name: app_wekan_app
    networks:
      - wekan-tier
    ports:
      - 10008:80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://todo.kerjean.me
      - MAIL_URL=smtp://user:pass@mailserver.example.com:25/
      - MAIL_FROM=wekan-admin@example.com
    depends_on:
      - wekandb

networks:
  wekan-tier:
    driver: bridge
```
