### ISSUE TITLE
Color customization : Dark

### ISSUE THREAD

**Issue by ckiltolier** [wekan/wekan#1149]
It would be nice to have the choice between white and dark grey for the main theme of your board.

For now we can just edit the top bar color, which is good.

But it would be nice to have the choice to put a dark main theme for the whole board.

Dark themes are good if you don't want to hurt your eyes while working :D 

Customization is not essential, but it really adds a nice feature in a soft ;)

**Comment by xet7** [comment]
@ckiltolier 

Please add screenshot of Wekan where you have modified colors to be dark.

**Comment by ckiltolier** [comment]
![dark wekan](https://user-images.githubusercontent.com/11541071/28684178-574c0852-72fb-11e7-9c39-d11281863c3a.png)

Actually I don't have the skills to do it. It's a request :D I'd like to have a dark option for wekan ;)

**Comment by xet7** [comment]
Ok :) I'll try with Stylish browser extension what it looks like, and see how to make those changes in Wekan.

**Comment by ckiltolier** [comment]
Yiha ! thx ;)

**Comment by zendre4** [comment]
+1

**Comment by lonix1** [comment]
It would be nice to have more than just gray - wekan needs a "dark mode".

May devs use dark mode in almost every tool (browser, IDE, terminal, various apps, etc.) so would be good to have wekan in dark as well. Changing between light-mode and dark-mode apps is always surprising while you're in "the zone".

**Comment by lonix1** [comment]
I created some css overrides with Stylish. It's not complete but I'm happy with it. I work in swimlanes mode, so that is what I changed (not list mode or calendar mode).

Colors:
- adds dark mode, I used vscode as a reference

Other:
- hides various useless icons and things
- hides  "add card", "add swimlane", "add list" links, until hovered (I find these very "noisy")

````css
/* HIDE PERMANENTLY -------------------------------------------------- */

/* logo */
.wekan-logo { display:none; }

/* header text */
#header-quick-access >ul >li:nth-child(1) >a { font-size:0; }
#header-quick-access >ul >li:nth-child(1) >a >.fa-home{ font-size:12px; margin:0; }

/* popup menu titles (boards, swimlanes, lists, cards, labels) */
.pop-over >.header { display:none; }

/* OPTIONAL 
   card fields: received, start, due, end, members, requested, assigned
   I rarely use these... uncomment if you want to hide them */
/*
.card-details-item.card-details-item-received,
.card-details-item.card-details-item-start,
.card-details-item.card-details-item-due,
.card-details-item.card-details-item-end,
.card-details-item.card-details-item-members,
.card-details-item.card-details-item-name { display:none; }
.card-details-items:empty { display:none; }
*/

/* HIDE UNTIL HOVER -------------------------------------------------- */

/* header "+" button */
#header-quick-access .fa-plus { display:none; }
#header-quick-access:hover .fa-plus { display:inherit; }

/* "add card" links (use visibility rather than display so items don't jump) */
                    .open-minicard-composer { visibility:hidden; }
.list.js-list:hover .open-minicard-composer { visibility:visible; }
                    .list-header-menu { visibility:hidden; }
.list.js-list:hover .list-header-menu { visibility:visible; }

/* "add list/swimlane" links (use visibility rather than display so items don't jump) */
.list.js-list-composer       >.list-header { visibility:hidden; }
.list.js-list-composer:hover >.list-header { visibility:visible; }

/* DARK MODE -------------------------------------------------- */

/* headers */
#header-quick-access, #header { background-color:rgba(0,0,0,.75) !important; }
#header .board-header-btn:hover { background-color:rgba(255,255,255,0.3) !important; }

/* backgrounds: swimlanes, lists */
.swimlane { background-color:rgba(0,0,0,1); }
.swimlane >.swimlane-header-wrap,
.swimlane >.list.js-list,
.swimlane >.list-composer.js-list-composer { background-color:rgba(0,0,0,.9); }

/* foregrounds: swimlanes, lists */
.list >.list-header, .swimlane-header { color:rgba(255,255,255,.7); }

/* cards */
.minicard { background-color:rgba(255,255,255,.4); color:#fff; }
.minicard:hover { background-color:rgba(255,255,255,.8) !important; color:#000; }
````

If anyone improves on this, please share here.
