### ISSUE TITLE
Cannot edit tasks with several members in the board

### ISSUE THREAD

**Issue by Davidbrcz** [wekan/wekan#1691]
## Issue

After adding a second member to any board, none of the members can edit the tasks. 
When clicking on one add information, the page does not load and we are stuck on a gray page. 
Removing the second board member does not reverse the issue.

I can edit a task (even if it is quite slow) as long as I'm the only member.

**Server Setup Information**:

Set up with  docker (I stripped other services). The docker compose is self sufficient 
```
version: "2"
 
services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-network
      - back-network
      - wekan-tier
    volumes:
      - ./conf/etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
        - /opt/srv/conf/etc/nginx/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
        - nginx
        

    
  wekandb:
    # All Wekan data is stored in MongoDB. For backup and restore, see:
    #   https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
    image: mongo:3.2.20
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
      
  wekan:
    # Wekan container only has Node.js and related code,
    # there is no data stored here.
    #
    # Docker Hub, usually broken:
    #image: wekanteam/wekan:latest
    #
    # Quay, usually works, updates faster:
    image: quay.io/wekan/wekan:v1.03
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    #---------------------------------------------------------------
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=wekan.domain.com
      - LETSENCRYPT_HOST=wekan.domain.com
      - LETSENCRYPT_EMAIL=contact@domain.com
      - VIRTUAL_PORT=80
      - ROOT_URL=http://wekan.domain.com
      - MONGO_URL=mongodb://wekandb:27017/wekan
    depends_on:
      - wekandb

networks:
  front-network:
    driver: bridge
  wekan-tier:
    driver: bridge
volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local
```

* Did you test in newest Wekan?: I tested docker image quay.io/wekan/wekan
* Wekan version: v1.03
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Debian 9 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: don't know 
* MongoDB Version: 3.2.20
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): 
 ROOT_URL=http://wekan.domain.com

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work*
![out](https://user-images.githubusercontent.com/5786937/41295275-753be5ac-6e5a-11e8-88c5-49fb6091df6e.gif)

- *Explain steps how to reproduce*

Create boards
Create task
Confirm you can edit it
Add member to board
Try to edit it

- *Attach log files in .zip file)*
`docker logs CONTAINER` does not provide anything meaningful
