### ISSUE TITLE
How to store logs in /var/log/syslog ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#2364]
Hello,

I use Wekan with the following docker-compose.yml file.
``` yml
version: '3'

services:

  wekandb:
    image: mongo:3.2.21
    command: mongod --smallfiles --oplogSize 128
    volumes:
      - wekan-mongodb_wekan-db:/data/db
      - wekan-mongodb_wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan:v2.23
    ports:
      - 80:8080
    deploy:
      replicas: 4

    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      [...]
    depends_on:
      - wekandb

volumes:
  wekan-mongodb_wekan-db:
    external: true
  wekan-mongodb_wekan-db-dump:
    external: true
```

I can see "live" logs with `docker service logs wekan_wekandb` but not with `docker service logs wekan_wekan` commands.

_Note: there is `"log-driver": "syslog",` in `/etc/docker/daemon.json` file._

Do you know how to store logs in `/var/log/syslog` for service wekan_wekan ?  
Or maybe it is already stored elsewhere ?

Thank you.
