### ISSUE TITLE
Lack of mongo resilience after unplanned shutdown.

### ISSUE THREAD

**Issue by wifimaclet** [wekan/wekan#2366]
Using stable Docker and latest docker-compose, my laptop overheated and emergency shut down kicked in due to reasons unrelated to wekan. After cooling down and powering back on, the containers started without error messages, but with an unclean shutdown warning from mongo. The boards were usable, but login was not, I was getting "Login Forbidden".

After some research (four hours divided in multiple days), I found the solution in Stack Overflow, apparently mongo doesn't self-repair when starting unless it has journaling enabled. I do not know how to enable journaling in mongo, but a `docker-compose down; docker-compose run wekandb mongod --repair; docker-compose up` fixed my issues.

**Comment by zombah** [comment]
```mongod --repair``` before mongo start adds significant timeout and may result in ECONREFUSED for wekan because mongo not ready yet. It is possible to mitigate that with
 healthcheck like this:
```
version: '2.1'
services:
  wekandb:
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/wekan --quiet
      interval: 10s
      timeout: 2s
      retries: 10
  wekan:
    depends_on:
      wekandb:
        condition: service_healthy
```
