### ISSUE TITLE
Request: Behaviors change request about the "custom field" auto creating and auto showing.

### ISSUE THREAD

**Issue by coleyon** [wekan/wekan#2392]
## Request

Behaviors change request about the "custom field" auto creating and auto showing.

**Current UX**:

1. Creates the customfield definition, with "Auto create field to all cards" and "Show field label on minicard" checkbox is ON.
![image](https://user-images.githubusercontent.com/24493192/57196073-4251a280-6f94-11e9-96ab-b5db70d4a1fe.png)
1. Firstly, create the new first card.
It does not matter which operation is pressed, either the Enter key or the Add button.
![image](https://user-images.githubusercontent.com/24493192/57196190-5cd84b80-6f95-11e9-8211-53d527785cae.png)
1. The second card inputting will begin, as soon as the first card has been registered.
At this time, the first card has a custom field displayed.
![image](https://user-images.githubusercontent.com/24493192/57196254-0f101300-6f96-11e9-8441-ffa0e5f46b05.png)
1. Complete the registration of the second card in the same way.
At this time, the second card has a no custom field displayed.
![image](https://user-images.githubusercontent.com/24493192/57196385-69f63a00-6f97-11e9-8d95-ec2860a73b33.png)

**Improvement Suggestion**:

Please change the behavior so that custom fields are automatically created and showed for the second and subsequent cards, when registering cards in the above operation.

**Server Setup Information**:

my wekan app environment is docker container, configures are below "docker-compose.yml" file.
this container upstarted by ```$ docker-compose up -d``` command.

```yaml
version: '2'
services:
  wekandb:
    image: mongo:3.2.21
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
  wekan:
    image: wekanteam/wekan:v2.59
    container_name: wekan-app
    restart: always
    ports:
      - 23680:8080
    environment:
      - TZ=Asia/Tokyo
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://$MYHOST_IP_ADDR:23680
      - WITH_API=true
      - LOGOUT_ON_HOURS=8
    depends_on:
      - wekandb
volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local
```
