### ISSUE TITLE
how to use external MongoDB

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2485]
I install the wekan in docker on my computer A(ip:88.88.88.47), it works. 
use http://88.88.88.47:27017/ on computer B and get "It looks like you are trying to access MongoDB over HTTP on the native driver port."

install wekan on computer B with below yml. 
===========my docker-compose.yml on computer B========================
version: '2'
services:
  wekan:
    image: wekanteam/wekan:v2.55
    container_name: wekan-app
    ports:
      - 81:8080
    environment:
      - MONGO_URL=http://88.88.88.47:27017/wekan
      - ROOT_URL=http://localhost:81 
      - MAIL_URL=smtp://user:pass@mailserver.example.com:25/ 
      - MAIL_FROM='Example Wekan Support <support@example.com>'
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local
=======================================
wekan-app can't be start with follow error message from "docker logs wekan-app" computer B:

Error: invalid schema, expected mongodb
    at module.exports (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:19:11)
    at connect (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:486:16)
    at Function.MongoClient.connect (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:250:3)
    at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at packages/idmontie_migrations.js:38:15
    at packages/idmontie_migrations.js:255:4

**Comment by javen9881** [comment]
please show help, thanks.

**Comment by xet7** [comment]
You should upgrade to newest Wekan, docker-compose.yml at https://github.com/wekan/wekan

You should not change mongodb url.

For root-url, see https://github.com/wekan/wekan/wiki/Settings

**Comment by javen9881** [comment]
thanks @xet7 
how to link the computer B wekan to the mongodb on computer A which are all established by docker on win10.?

thanks again.

**Comment by xet7** [comment]
```
services:
  wekandb:
    image: mongo:3.2.21
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

wekan:
  image: wekanteam/wekan:v2.55
  container_name: wekan-app
  ports:
  - 81:8080
  environment:
  - MONGO_URL=mongodb://wekandb:27017/wekan
  - ROOT_URL=http://88.88.88.47:81
  - MAIL_URL=smtp://user:pass@mailserver.example.com:25/
  - MAIL_FROM='Example Wekan Support support@example.com'
  - WITH_API=true
  - BROWSER_POLICY_ENABLED=true

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
driver: bridge
```
On other computer browse to http://88.88.88.47:81
