### ISSUE TITLE
Some users cannot switch views or languages

### ISSUE THREAD

**Issue by timothyparez** [wekan/wekan#2630]
![wekanswitch](https://user-images.githubusercontent.com/2060470/63154619-995f1d00-c043-11e9-8bcf-2465981c4d4c.gif)
## Issue

Some users cannot switch views or languages,  
when they click to do so it switches and then jumps back.

This behavior is shown in the attached gif

 - It applies to all boards
 - It does not apply to all users
 - It occurs on Firefox and Chrome on Windows and Linux
 - It occurs for both the Chinese and English language versions (did not test others)
 - The only information displayed in the browser log is `access denied` in what looks to be a script with some random name.  

*Wekan Version:* Latest official docker image (we update every night)
*Frontend:* Nginx 

Wekan: 3.20.0
Meteor: 1.8.1
Node: 8.16.0
MongoDB: 4.2.0

**Comment by timothyparez** [comment]
It seems like
 - Users who registered with the page set to Chinese cannot switch views
 - Users who registered with English cannot switch to Chinese

**Comment by timothyparez** [comment]
The docker-compose file for this instance:

```
db:
  image: mongo
  volumes:
    - ./data/db:/data/db
    - ./data/backups:/backups
  command: mongod 
  #--smallfiles


wekan:
  image: wekanteam/wekan
  #  volumes:
  #        ./public:/built_app/programs/web.browser/app
  environment:
          - MONGO_URL=mongodb://db:27017/wekan
          - VIRTUAL_HOST=correcthostherebutremovedforbugreport.com
          - MAIL_URL=127.0.0.1
          - ROOT_URL=https://correcturlherebutremovedforbugreport.com
  links:
          - db:db
  ports:
          - 32111:80
          - 32112:8080
```
