### ISSUE TITLE
Bug: Drag handle is on top of list menu

### ISSUE THREAD

**Issue by gerroon** [wekan/wekan#2827]
Hi,

I am using the Docker-compose to run this. I just pulled 3.56 and Firefox (70 on Linux) never finishes loading a page , until I do couple manual refreshes. Changing from board to board does not happen successfully as in it changes the board but it still shows the old board content, clearly a rendering issue.

Chromium seems to have no issue with this. It runs fine in it. 

Bear in mind that this issue just started happening with the latest docker pull, I think I was using 3.54 before, so I will roill back to that one. However I thought that I would report this.

Here is the erros I see in Firefox 70 console. And I do not se any logs generated with `docker logs -f wekan-app`

```

Wekan Version	3.56.0
Meteor version	1.8.2
Node version	8.16.2
MongoDB version	4.0.11
```

Apache Proxy
```
 ProxyPassMatch "^/(sockjs\/.*\/websocket)$" "ws://127.0.0.1:3000/$1"
        ProxyPass "/wekan" "http://127.0.0.1:3000/wekan"
        ProxyPassReverse "/wekan" "http://127.0.0.1:3000/wekan

```

FF console (not sure if it is related)

``` 

https://DOMAIN/wekan/informationInvalid X-Frame-Options: “ALLOW-FROM” header from “https://DOMAIN/wekan/b/dkuMyPy9SjpbWEjCy/XXXXX” loaded into “https://DOMAIN/wekan/b/oPcepbD68umCywfsP/board”.

Firefox can’t establish a connection to the server at wss://DOMAIN/wekan/sockjs/568/cb2qs1ne/websocket. 0e3f5ad6a550ed1d08e8950011ec98a6a92a839d.js:81:17863

The connection to wss://DOMAIN/wekan/sockjs/568/cb2qs1ne/websocket was interrupted while the page was loading. 

```

**Comment by gerroon** [comment]
I was wrong about the versions. It seems like this issue started with versions after 3.49. I just tested it with 3.49 and it seems to work in FF 70

**Comment by xet7** [comment]
@gerroon 

Do you have Apache Mod_Proxy enabled?
https://github.com/wekan/wekan/wiki/Apache#1-enable-mod_proxy

Your ProxyPassMatch ending is incorrect, it's like running on Main URL that is recommended:
https://github.com/wekan/wekan/wiki/Apache#a-main-url

But remaining of your settings ProxyPass and ProxyPassReverse are like running like SubURL that is not recommeded, because could cause issues with avatars etc if needing to change URL later.
https://github.com/wekan/wekan/wiki/Apache#b-sub-url

I don't have any errors with Caddy, Wekan v3.56 and Firefox 70.0.1.

**Comment by xet7** [comment]
If you are running Wekan in iframe, you need to set trusted-url to your website address that has html that has Wekan in iframe:
```
sudo snap set wekan trusted-url='https://example.com'
```
If you need to turn of all iframe protections, allowing all iframing, that is not recommended for public Internet use, you can do so with:
```
sudo snap set wekan browser-policy-enabled='false'
```
Descriptions of these settings are also at:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys#list-of-supported-keys

You can get list of all Wekan settings with:
```
wekan.help | less
```

**Comment by gerroon** [comment]
@xet7 

Ues I have mod proxy enabled since I have been using Wekan for almost a year without any issues. I am also running this under Docker so the Snap lines is no use to me.

Is there a way to set those in Docker?

It is also interesting that I did not notice these issues until I upgraded to 3.56.

**Comment by xet7** [comment]
Yes, settings are at docker-compose.yml at https://github.com/wekan/wekan

**Comment by xet7** [comment]
You can also use just docker commands without docker-compose, like this:
https://github.com/wekan/wekan/wiki/Docker

**Comment by gerroon** [comment]
Thanks, I browserd through to see what I need in my current compose file, But I am not an expert on these issues.

This is my current working compose (except the db)

```
   wekan:                                                                                                                                                                                                         
      image: wekanteam/wekan                                                                                                                                                                                       
      container_name: wekan-app                                                                                                                                                                                    
      restart: always                                                                                                                                                                                              
      networks:                                                                                                                                                                                                    
        - wekan-tier                                                                                                                                                                                               
      ports:                                                                                                                                                                                                       
        - 3005:8080                                                                                                                                                                                                
      environment:                                                                                                                                                                                                 
        - MONGO_URL=mongodb://wekandb:27017/wekan                                                                                                                                                                  
        - ROOT_URL=https://DOMAIN/wekan                                                                                                                                                                     
        - WITH_API=true                                                                                                                                                                                            
        - RICHER_CARD_COMMENT_EDITOR=true                                                                                                                                                                          
        - BROWSER_POLICY_ENABLED=true
        - LDAP_BACKGROUND_SYNC_INTERVAL=''
        - TRUSTED_URL=https://DOMAIN
      depends_on:                                                                                                                                                                                                  
        - wekandb                                                                                                                                                                                                  
  volumes:                                                                                                                                                                                                         
    wekan-db:                                                                                                                                                                                                      
      driver: local                                                                                                                                                                                                
    wekan-db-dump:                                                                                                                                                                                                 
      driver: local                                                                                                                                                                                                
  networks:                                                                                                                                                                                                        
    wekan-tier:                                                                                                                                                                                                    
      driver: bridge               
```
