### ISSUE TITLE
Building from source using docker compose fails

### ISSUE THREAD

**Issue by tamasberesoebb** [wekan/wekan#3228]
## Issue
Hello

I wanted to check out the source code, make some styling changes and build it from source using Docker. It failed.

* Wekan version:
Checked out master branch source code
Commit:
https://github.com/wekan/wekan/commit/1050e04c10c69d76a6489308a02097ab0766f121

* Operating System:
ubuntu server 20.04

**Problem description**:
I have updated docker compose according to the instructions:
```
    # ==== BUILD wekan-app DOCKER CONTAINER FROM SOURCE, if you uncomment these ====
    # ==== and use commands: docker-compose up -d --build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=v12.18.3
        - METEOR_RELEASE=1.10.2
        - NPM_VERSION=latest
        - ARCHITECTURE=linux-x64
        - SRC_PATH=./
        - METEOR_EDGE=1.5-beta.17
        - USE_EDGE=false
```
The args values I have copied over from the Dockerfile.

`docker-compose up -d --build`

It fails:

```
+ gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build
/home/wekan/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, copyfile '/home/wekan/app/packages/wekan-ldap/.npm/package/node_modules/.temp-1j793j6.gw9w/node_modules/dtrace-provider/.gitmodules' -> '/home/wekan/app/packages/wekan-ldap/.npm/package/node_modules/dtrace-provider/.gitmodules'
    at Object.copyFileSync (fs.js:1807:3)
```

See full log in this file:
[docker_compose_logs.txt](https://github.com/wekan/wekan/files/5034540/docker_compose_logs.txt)

Are those arguments wrong, or am I missing something?

The documentation is not so great:
https://github.com/wekan/wekan/wiki/Developer-Documentation

`Docker up-to-date way: You can clone wekan/wekan repo and update docker-compose.yml file ROOT_URL etc as documented at https://github.com/wekan/wekan-mongodb commented docker-compose.yml file, install docker, and build from source with docker with "docker-compose up -d --build"`

That will actually not build it from source. I also had to uncomment a few lines in the docker compose file. I guess "update docker-compose.yml file ROOT_URL etc" also covers the other changes, but maybe mention that it will not build it from source without many other changes (not just the ROOT_URL).
`BUILD wekan-app DOCKER CONTAINER FROM SOURCE, if you uncomment these`
