### ISSUE TITLE
Contribute k8s/kustomize deployment

### ISSUE THREAD

**Issue by blaggacao** [wekan/wekan#3262]
I'd like to contribute a fully functional k8s `kustomize` empowered deployment, usually projects use subfolders `./k8s` or &mdash; mostly &mdash; `./deloy` for this. Would `./deploy` be ok as attachment point?

Out of the below tree, `2-deploy` & `3-playground` are the relevant modules that I'd like to contribute:
```console
$ tree 00-bases
00-bases
├── 0-src
├── 1-artifacts
├── 1-artifacts.example
│   ├── my-docker-image
│   │   └── Dockerfile
│   ├── my-nix-image
│   │   └── default.nix
│   └── Nixfile.nix
├── 2-deploy
│   ├── deployment.yaml
│   └── kustomization.yaml
├── 3-playground
│   ├── env-configmap.yaml
│   ├── kustomization.yaml
│   └── mongo-db-external-srv.yaml
├── skaffold.yaml
└── skaffold.yaml.example

```

---

Similarly what's the correct (best) attachment point in the whole github/wekan orga to contribute a working DexIDP config example (once I got it working)?

**Comment by xet7** [comment]
@blaggacao 

If `k8s` works, it would be better, because from general `deploy` I have hard time figuring out for what platform deploy it is. Wekan is available for many platforms.

If `k8s` does not work directly without modifications, then `deploy` is OK.

You can submit pull request to `https://github.com/wekan/wekan` master branch.

**Comment by xet7** [comment]
@blaggacao 

For DexIDP you can create that directory also to wekan repo root, like wekan/DexIDP

**Comment by blaggacao** [comment]
If a kustomize example where on has to bring ones own mongodb would be interesting, maybe I can prepare a PR in the next few minutes? &mdash; since kustomize users might construe their platform in a way that uses for example a mongodb operator (as we do). Thoughts? I can follow up with a mongodb deployment included, after that.

**Comment by xet7** [comment]
It would be nice to have most config available as ready as possible, and also a `README.md` for instructions in that directory, similarly like in openshift and torodb-postgresql directories.

**Comment by xet7** [comment]
Currently I have most documentation at https://github.com/wekan/wekan/wiki .

Docs were originally moved to wiki for contributions, so they would be editable by all logged in GitHub users. But then become problem, that because some newbies did not understand why wiki was editable, those newbies did create some test pages with text about wondering why wiki is editable. So I had to disable editing by any logged in GitHub user. I'm thinking should I move those docs back to Wekan repo.

Sure there has been some attempts for creating nicer looking documentation like at https://github.com/wekan/wekanhow and https://github.com/wekan/wekan-doc , but those have only are at beginning stages.

The benefit of current Wekan GitHub wiki is that those are already linked to at many places at issues, and they are first hits at search engines.

**Comment by blaggacao** [comment]
I'm quite almost there, maybe I can ask for a little help with the mongodb security settings which seems to be the point holding me back to publish a fully working kustomize example. I think I'll include the dexidp example as variant to it (since it's also based on kustomize &mdash; appealing to the whole idea of kustomize to make composable deployments easy). Here is my current mongodb security config, but it doesn't work:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: wekan-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    # this user configuration is not right ...
    - name: wekan
      db: admin
      passwordSecretRef:
        name: wekan-mongodb-user-credential
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
```

The uri used is: `mongodb://wekan:wekan@wekan-mongodb-svc:27017?authSource=admin` &mdash; the `wekan-mongodb-user-credential` secret is set to `wekan`, too.

It complains of not having certain rights to do certain things... What should be a expected working set of user ACL for wekan?
