### ISSUE TITLE
Error trying to send email: Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by johackim** [wekan/wekan#3896]
Since version 5.02, I can't send emails.

I receive this error : 

```
Sending email failed
Error trying to send email: Hostname/IP does not match certificate's altnames: Host: xyz.com. is not in the cert's altnames: DNS:xyz.com
```

Here my docker configuration : 

```yaml
version: '3.7'

services:
  wekan:
    image: wekanteam/wekan:${VERSION:-v5.35}
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan
      - VIRTUAL_HOST=${DOMAIN}
      - ROOT_URL=https://${DOMAIN}
      - MAIL_URL=${MAIL_URL:-smtps://user:password@xyz.com:587} # or smtps://user:password@xyz.com:587/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false
      - MAIL_FROM=${MAIL_FROM:-noreply@xyz.com}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.wekan.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.wekan.entrypoints=https
        - traefik.http.routers.wekan.service=wekan
        - traefik.http.routers.wekan.tls.certresolver=letsencrypt
        - traefik.http.services.wekan.loadbalancer.server.port=8080
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    volumes:
      - mongo:/data/db
    networks:
      - internal

volumes:
  mongo:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
```
