### ISSUE TITLE
Publish helm chart to Artifact HUB to improve visibility

### ISSUE THREAD

**Issue by luclu** [wekan/wekan#4051]
Could you kindly add this chart to https://artifacthub.io/ to improve visibility?

Artifact HUB is a CNCF Sandbox project and also endorsed by Helm:
- https://hub.helm.sh/
- https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository

**Comment by xet7** [comment]
I also checked that I do not have adblocking enabled. It did not make ID visible.

**Comment by varac** [comment]
> @varac Do you know how to get this working?

I don't, since I haven't published charts on Github before. But @Gabisonfire and @luclu provided already good instructions. Hope you get it set up soon, I'm happy to test it once it's online!

**Comment by varac** [comment]
@xet7 I created https://github.com/wekan/charts/pull/3 to fix the helm repo

**Comment by xet7** [comment]
@varac 

Did I add Artifact Hub ID to correct branch? https://github.com/wekan/charts/commit/9d28a4c32c4f35b6daa63825b96aba6767ab81ce

**Comment by varac** [comment]
Yes: 
```
❯ curl  https://wekan.github.io/charts/artifacthub-repo.yml 
repositoryID: f6dde1c7-7cc4-4053-870c-0dc6a73d9ac9
owners:
  - name: wekan
    email: support@wekan.team
  - name: xet7
    email: x@xet7.org
```
