### ISSUE TITLE
Authelia OAUTH2-Settings

### ISSUE THREAD

**Issue by tamaskan** [wekan/wekan#4210]
I couldn't find an example for authelia inside docker-compose.yml.  According to https://www.authelia.com/docs/community/oidc-integrations.html both should work together with these endpoints: https://www.authelia.com/docs/configuration/identity-providers/oidc.html .

**Comment by carl-unique** [comment]
i used following config for wekan

```
      # ==== OAUTH - Authelia ====
      - OAUTH2_ENABLED=true
      
      # only required if using self-signed / own ca - but gets ignore
      #- OAUTH2_CA_CERT=/etc/ssl/certs/ca-certificates.crt  # does not work
      # - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

      # ==== AUTOLOGIN WITH OIDC/OAUTH2 ====
      # https://github.com/wekan/wekan/wiki/autologin
      - OIDC_REDIRECTION_ENABLED=false
      - OAUTH2_CLIENT_ID=<CLIENT-ID>
      - OAUTH2_SECRET=<SECRET>
      - OAUTH2_SERVER_URL=https://authelia.kind.local/
      - OAUTH2_AUTH_ENDPOINT=api/oidc/authorization
      - OAUTH2_USERINFO_ENDPOINT=api/oidc/userinfo
      - OAUTH2_TOKEN_ENDPOINT=api/oidc/token
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_ID_MAP=sub
      # The claim name you want to map to the username field:
      - OAUTH2_USERNAME_MAP=preferred_username
      # The claim name you want to map to the full name field:
      - OAUTH2_FULLNAME_MAP=name
      # The claim name you want to map to the email field:
      - OAUTH2_EMAIL_MAP=email
      # groups is not used, might be a todo in the future?
      - OAUTH2_REQUEST_PERMISSIONS=openid profile email
```


for authelia i used

```
        - client_id: 'wekan-client'
          client_name: 'wekan-client'
          client_secret: '$pbkdf2-sha512$...'
          public: false
          authorization_policy: 'one_factor'
          require_pkce: false
          pkce_challenge_method: ''
          redirect_uris:
            - https://wekan.kind.local/_oauth/oidc
          scopes:
            - 'openid'
            - 'profile'
            - 'email'
          response_types:
            - 'code'
          grant_types:
            - 'authorization_code'
          access_token_signed_response_alg: 'none'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_post'

```

**Comment by carl-unique** [comment]
For dex it is even easier

```
  - id: wekan-client
    redirectURIs:
      - https://wekan.kind.local/_oauth/oidc
    name: wekan-client
    secret: my-wekan-SECRET
    scopes:
      - openid
      - profile
      - email
```

in wekan:
```
- OIDC_REDIRECTION_ENABLED=false
- OAUTH2_CLIENT_ID=wekan-client
- OAUTH2_SECRET=my-wekan-SECRET
- OAUTH2_SERVER_URL=https://dex.kind.local/
- OAUTH2_AUTH_ENDPOINT=auth
- OAUTH2_USERINFO_ENDPOINT=userinfo
- OAUTH2_TOKEN_ENDPOINT=token
- OAUTH2_LOGIN_STYLE=redirect
- OAUTH2_ID_MAP=sub
# The claim name you want to map to the username field:
- OAUTH2_USERNAME_MAP=preferred_username
# The claim name you want to map to the full name field:
- OAUTH2_FULLNAME_MAP=name
# The claim name you want to map to the email field:
- OAUTH2_EMAIL_MAP=email
- OAUTH2_REQUEST_PERMISSIONS=openid profile email

```
