### ISSUE TITLE
Update to V6.09 or V6.11 fails

### ISSUE THREAD

**Issue by scott-dunt** [wekan/wekan#4416]
Wekan will run on V6.05  But if I update to V6.09 or V6.11 (latest Quay.io images) wekan - app fails during start up; (mongo seems fine..)
```
wekan-app  | > Starting migrate-attachments-collectionFS-to-ostrioFiles migration.
wekan-app  | create storagePath because it doesn't exist: ./wekan-uploads
wekan-app  | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekan-app  |       throw error;
wekan-app  |       ^
wekan-app  |
wekan-app  | Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
wekan-app  |     at new ObjectID (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:34:11)
wekan-app  |     at Object.createReadStream (packages/cfs:gridfs/gridfs.server.js:75:14)
wekan-app  |     at Object.self.adapter.createReadStreamForFileKey (packages/cfs_storage-adapter.js:104:39)
wekan-app  |     at FS.Transform.createReadStream (packages/cfs_storage-adapter.js:404:35)
wekan-app  |     at Object.self.adapter.createReadStream (packages/cfs_storage-adapter.js:114:51)
wekan-app  |     at FS.File.createReadStream (packages/cfs_file.js:833:30)
wekan-app  |     at server/migrations.js:1147:32
wekan-app  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
wekan-app  |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
wekan-app  |     at Object.migrationCallback (server/migrations.js:1136:25)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:273:30)
wekan-app  |     at /build/programs/server/boot.js:415:15
wekan-app  |     at /build/programs/server/boot.js:465:7
wekan-app  |     at Function.run (/build/programs/server/profile.js:280:14)
wekan-app  |     at /build/programs/server/boot.js:463:13
wekan-app exited with code 1

```

Running in Docker from quay.io images.  works on V6.05 image, but fails on V6.09 and V6.11.
```
WeKan ® Version	6.05.0
Meteor version	2.2
Node version	12.22.10
MongoDB version	4.4.13
MongoDB storage engine	wiredTiger
MongoDB Oplog enabled	
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.14.268-205.500.amzn2.x86_64
OS Uptime	1 days, 10 hours, 16 seconds
OS Load Average	1.01, 0.56, 0.35
OS Total Memory	8 GB
OS Free Memory	166 MB
OS CPU Count	2
```
```docker-compose.yml
version: '2'

services:

  wekandb:
    image: mongo:4.4
    container_name: wekan-db
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: Wekan_Mongo_DB
    command: mongod --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan@sha256:0e2df1aefd2e5f0115ef88d279df60b7ae82533ef2d654d143866dbf9a69c505
    container_name: wekan-app
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: Wekan

    networks:
      - wekan-tier
    ports:
     - 3001:8080
    volumes:
      - /home/ec2-user/wekan/Attachments:/home/ec2-user/wekan/Attachments
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://wekan.vvbcbcbcbc.dev  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtps://<<SNIP>>&secureConnection=true
      - MAIL_FROM=cbcbcb@hsjsjsklsdfnlsdjkflaskdjflaskdfj.com
      - WITH_API=true
      - ATTACHMENTS_STORE_PATH=/home/ec2-user/wekan/Attachments # pathname can be relative or fullpath
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - DEBUG=true
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
       - OAUTH2_CLIENT_ID=sdkljasdlfkjasldfkjasldfkjasdlfjksdl;fkjasdl;fkjasd
      - OAUTH2_SECRET=klsdjlksdjflsdjfl;sdjfl;sjdfl;sjdfl;ksdjf
      - OAUTH2_SERVER_URL=kldlkasjflajsdflajsdfljksdfl;kjs;lksdjflasdf
      - OAUTH2_AUTH_ENDPOINT=/oauth2/v2.0/authorize
      - OAUTH2_USERINFO_ENDPOINT=klsjdlkasjdflasjfljksf;lasjkdf;laskdjf
      - OAUTH2_TOKEN_ENDPOINT=/oauth2/v2.0/token
      - OAUTH2_ID_MAP=email
      - OAUTH2_USERNAME_MAP=email
      - OAUTH2_FULLNAME_MAP=name
      - OAUTH2_EMAIL_MAP=email
    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
```
Not sure if this is attachment related. Where did the attachment settings in docker-compose.yml GO?  I cannot find any migration instructions.

**Comment by mfilser** [comment]
Did you configure the WRITABLE_PATH environment variable and a volume mount?

https://github.com/wekan/wekan/blob/90be8ff936bd7edb1c67c6c296640509f8bfdc66/docker-compose.yml#L329

**Comment by scott-dunt** [comment]
Tried that, no joy. I'm not 100% sure of the relationship between  ATTACHMENTS_STORE_PATH and WRITABLE_PATH. so I created a subdirectory in the already existing volume mount called uploads and set the WRITABLE_PATH to point to it..

docker-compose.yml:
```yaml
wekan:
    container_name: wekan-app
<snip>
volumes:
      - /home/ec2-user/wekan/Attachments:/home/ec2-user/wekan/Attachments
 environment:
<snip>
 # ==== STORE ATTACHMENT ON SERVER FILESYSTEM INSTEAD OF MONGODB ====
 # https://github.com/wekandoc/wekan/pull/2603
- ATTACHMENTS_STORE_PATH=/home/ec2-user/wekan/Attachments

 # ==== WRITEABLE PATH FOR FILE UPLOADS ====
 - WRITABLE_PATH=/home/ec2-user/wekan/Attachments/uploads
```
Still fails. but slightly different error:

```
wekan-app  | > Starting migrate-attachments-collectionFS-to-ostrioFiles migration.
wekan-app  | /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
wekan-app  |       throw error;
wekan-app  |       ^
wekan-app  |
wekan-app  | Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
wekan-app  |     at new ObjectID (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:34:11)
wekan-app  |     at Object.createReadStream (packages/cfs:gridfs/gridfs.server.js:75:14)
wekan-app  |     at Object.self.adapter.createReadStreamForFileKey (packages/cfs_storage-adapter.js:104:39)
wekan-app  |     at FS.Transform.createReadStream (packages/cfs_storage-adapter.js:404:35)
wekan-app  |     at Object.self.adapter.createReadStream (packages/cfs_storage-adapter.js:114:51)
wekan-app  |     at FS.File.createReadStream (packages/cfs_file.js:833:30)
wekan-app  |     at server/migrations.js:1147:32
wekan-app  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1141:16)
wekan-app  |     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:920:44)
wekan-app  |     at Object.migrationCallback (server/migrations.js:1136:25)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:273:30)
wekan-app  |     at /build/programs/server/boot.js:415:15
wekan-app  |     at /build/programs/server/boot.js:465:7
wekan-app  |     at Function.run (/build/programs/server/profile.js:280:14)
wekan-app  |     at /build/programs/server/boot.js:463:13
```

**Comment by koelle25** [comment]
I also get the `Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`.

Here's my docker-compose.yml:
```yml
version: '3.7'
services:
  db:
    image: mongo:${MONGODB_VERSION}
    container_name: wekan_db
    restart: unless-stopped
    # Log to stdout:
    command: mongod --oplogSize 128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db:/data/db
      - db-dump:/dump

  wekan:
    image: wekanteam/wekan:${WEKAN_VERSION}
    container_name: wekan
    restart: unless-stopped
    ports:
      - "8086:8080"
    environment:
      - WRITABLE_PATH='/data'
      - MONGO_URL='mongodb://db:27017/wekan'
      - ROOT_URL='https://wekan.my.company'
      - MAIL_URL='smtps://noreply@my.company:*****@smtp.office365.com:587/'
      - MAIL_FROM='WeKan Notifications <noreply@my.company>'
      - WITH_API='true'
      - RICHER_CARD_COMMENT_EDITOR='false'
      - CARD_OPENED_WEBHOOK_ENABLED='false'
      - MAX_IMAGE_PIXEL='1280'
      - IMAGE_COMPRESS_RATIO='80'
      - BIGEVENTS_PATTERN='NONE'
      - BROWSER_POLICY_ENABLED='true'
      - DEFAULT_AUTHENTICATION_METHOD='ldap'
      - LDAP_ENABLE='true'
      ... [other LDAP settings]
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - attachments:/data:rw

volumes:
  attachments:
    driver: local
    driver_opts:
      type: nfs4
      device: '${SAN_BASEPATH}/attachments'
      o: addr=${SAN_IP},rw
  db:
    driver: local
    driver_opts:
      type: nfs4
      device: '${SAN_BASEPATH}/db'
      o: addr=${SAN_IP},rw
  db-dump:
    driver: local
    driver_opts:
      type: nfs4
      device: '${SAN_BASEPATH}/db-dump'
      o: addr=${SAN_IP},rw
```
(`SAN_BASEPATH` and `SAN_IP` are defined in a .env file)

The content of the `attachments` volume (sensitive values replaced with ***):
```
'9eWFDXAZmZ8KRoeNw-Angebot AHK Gespra'$'\314\210''ch *** heute.pdf'
 LKgqiYKT3PxWQ4HBq-Angebot_***_AHK_v3.docx
'R2ZtpzxEWrzR8SwTi-Abrechnungsvereinfachungen in ***.pdf'
 attachments-2XySfoufEp9Hs2A5q-Newsletter_Verteiler.docx
attachments-2rruCP5gTZLj673Gz-Agenda_2_Team_23.03.2020.pptx
 attachments-36FvGEZuqkvxq4Cyg-***_Strategie_v2019_02.pptx
 attachments-4CS3YKL8vu7oWcdpp-***.pdf
'attachments-4zJijhbBGdpMjTCCr-*** Newsletter_Nr.1_April 2020.pdf'
'attachments-54JsR4e7RdZjfruxs-LED Leuchtwand_1.jpg'
 attachments-5PQsRxuA8hMR9BZeA-Logo_***.jpg
 attachments-5Wf54KBjdcgkBtf4u-PRO-613014-***.pdf
 attachments-5hiqcG6SnBMiAJMqb-Protokoll_6_Team_20.04.pptx
 attachments-66ihYoTZ5ZrFzQG2C-Entwurf_Workshop_Raumplan.pdf
 attachments-8ueQgHNiSg8BaqP9Z-Agenda_7_Team_27.04.2020.pptx
 attachments-Aqr3NTBYx45x9YEDK-Massnahmenliste_20200420_***_v1_BB.ppt
'attachments-Bn5DmgAtMuvQTuYDC-Bildschirmfoto 2019-08-14 um 10.33.43.png'
 attachments-CegsSC82Gf9xfGzHe-Agenda_1_***_09.06.2020.pptx
 attachments-CwyjT59MALJS9EMAg-Homepage.png
 attachments-DmFEkEo796Hyvhph2-Checkliste_Veranstaltungen_2019_03_28.pdf
 attachments-EJWfsiGCTD6xwTrCz-Agenda_1_***_30.06.pptx
'attachments-FLQjrpT9aLzpYkCXG-*** Newsletter (DE)_August.pdf'
 attachments-Fgsr7cp9BzPkCkEb9-LK_20210202.ppt
 attachments-G5QTEDwvxcoxANWvs-***.pdf
 attachments-GtbHn8KD8YakjNCJc-Visitenkarte.jpg
 attachments-J3XGyYjZo4yqKSR9D-Model_three_plus_two_v001.pptx
 attachments-JKjsbHiqT7JA5LAtx-***.jpg
'attachments-JzsmyRRgwTiXtJcxe-Bestellung_ Werbematerial_*** Shop.pdf'
'attachments-LCcXss8zFkiGBFupL-NL_*** 22-06-2020.pdf'
 attachments-LDNX2usBaXuXFAWMK-Agenda_8_Team_04.05.2020.pptx
 attachments-LG85wLYTmq9j3LLw3-Agenda_5_Team_14.04.2020.pptx
 attachments-LrcbkShGDoX7rA4nt-Protokoll_11_Team_26.05.pptx
'attachments-LxZAGxEvMjJt43dMj-Bildschirmfoto 2019-08-14 um 10.37.25.png'
 attachments-MPAcTXW4F8gbQzqnx-Protokoll_7_Team_29.04.2020.pptx
 attachments-NZsEdypTLMsexq6Hr-Agenda_6_Team_20.04.2020.pptx
 attachments-Q3WHktBA9GozBJint-Agenda_1_Team_18.03.2020.potx
'attachments-Q7vfq6vuevHtSuJHP-ETNC Special Report_Covid-19_*** 2020.pdf'
 attachments-QRisBpPJuuXdh68wh-Anmeldung_***+_08.pdf
 attachments-RBfpckWNpYdDjLAGR-Glossar_***_ZY.docx
 attachments-RpfFjaByLbbAMpyxg-***_CN_ZY.docx
 attachments-SHRC3Y9YmBCXa445T-Agenda_5_Team_14.04.2020.pptx
 attachments-T3Av2EsXdmC4afswg-v2_LK_20210202.pptx
 attachments-TQfT6TtvugF3JrQoY-Protokoll_10_Team_20.05.pptx
 attachments-W47JpwwNeb3FidwHM-Protokoll_8_Team_04.05.2020.pptx
'attachments-WxRYJ9AsgjsWPpESy-Internetpra'$'\314\210''senz ***.docx'
'attachments-XE4KXhPaPDK5rR6X2-'$'\345\244\232\347\211\271\350\222\231\345\276\267\344\270\255\345\233\275\350\203\275\345\212\233\344\270\255\345\277\203''.pdf'
 attachments-XtuocLMLCX6Dj7FuT-CCST.png
'attachments-YmhiZ4TrAp6KHChMf-Final_long_Sachbericht zum Zwischennachweis_01.04-2.pdf'
 attachments-ZLca8HuWr7rKDEji6-Protokoll_9_Team_11.05.2020.pptx
'attachments-a52KRyigCRfAY3xcC-Final_long_Sachbericht zum Zwischennachweis_01.04-2.docx'
'attachments-cCy5d4JtQWddPaR7h-LED Leuchtwand_2.jpg'
 attachments-crCh44nQsAhkoHTb8-Agenda_9_Team_11.05.2020.pptx
 attachments-crGJsMJzH5rroKEhL-Agenda_11_Team_26.05.2020.pptx
 attachments-dhp3MmaRbrZcw22Aa-Protokoll_14_Team_17.06.2020.pptx
'attachments-fFty4cxHNiGZdWLjX-Bildschirmfoto 2019-09-04 um 17.28.04.png'
 attachments-frTbBbgTQMiEtM82E-3+2.png
'attachments-h5K6Xr2J4Y9bn8Ls3-Bildschirmfoto 2019-08-14 um 13.22.37.png'
 attachments-hTS4Bo4hNk44suJ26-Newsletter:Verteiler.docx
'attachments-hYcJ4Fz5oojWwX3dG-Gru'$'\303\237''wort vom ***.docx'
'attachments-imMd6v3CnSFCLHAka-Rede ***_6.2019_Berlin.docx'
 attachments-ko2PPLDxrSBhfqSHc-education+.png
'attachments-m53eCiXyDD2EX8dxz-Bildschirmfoto 2019-09-04 um 17.25.26.png'
 attachments-m6CFdbooBsMZ8AjHr-11_2019_Event_Ablaufplanung__v1.doc
'attachments-n7ZMHE3Ayk8im8Dkw-*** Newsletter (CN)_Ausgabe 2.pdf'
 attachments-ng8J5EjC3oNudfzSQ-Kanban.png
'attachments-noY9KtWXd7HduHRm9-Checkliste Teilnehmer.doc'
'attachments-ocNMifG48PxMFEQoc-Vorlage 2_Agenda_Workshop_30_11-1_12_2020.doc'
 attachments-qsm8sH732Nr8RcobN-***_20190313.pdf
'attachments-rFoNbcBR7gmYKk9r3-Agenda Lenkungskreis 13-10-2020.pdf'
 attachments-rMksmFGCPE6pJ2jEK-Agenda_14_Team_17.06.pptx
 attachments-rvxtnL4bqRQrzQMrs-Agenda_4_Team_30.03.2020.pptx
'attachments-tXCbXDhiCuDouc9a3-Agenda *** 09-09-2020.pdf'
 attachments-tyG4M9YHnwWiKv7fp-11_2019_Event_Ablaufplanung_v14.10.19.doc
'attachments-v5NfnWpYfhT4TCZit-*** Newsletter_Nr.2_Mai 2020.pdf'
'attachments-vmBXWpzSSanvT7Gwp-Final_short_Sachbericht zum Zwischennachweis_01.04-2.docx'
 sAnMjjhznHEjJpzN6-image.png
 uploads
'vTEjkzCT7KsWNdM6h-Anlage zu ***_11.2019.docx'
```

I suspect some special characters are the problem here?
