### ISSUE TITLE
Empty site when testing wekan with docker-compose.yml

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [wekan/wekan#4513]
## Issue
I get an empty site when browsing the wekan url.

### Server Setup Information

* Did you test in newest Wekan?:
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System: Ubuntu 20.04.4 LTS x86_64
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): none
* Node.js Version: 
* MongoDB Version: 
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? edge, firefox, opera, chrome

I'm just tryint to use the bare minimum docker-compse.yml to have a quick look and all I'm getting is blank site

```
---
version: '2'

services:

  wekandb:
    image: mongo:5
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 8111:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw

volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local


networks:
  wekan-tier:
    driver: bridge
```

The only output I can see in the portainer's wekan-app log is:

{"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Tue May 17 2022 12:58:56 GMT+0000 (Coordinated Universal Time)","time":{"$date":1652792336857},"level":"info"}
