### ISSUE TITLE
Covers not visible in Cards

### ISSUE THREAD

**Issue by corincorvus** [wekan/wekan#4541]
### Server Setup Information
Server:
Debian 64 Bit Bullseye with Docker
6GB Ram
4 Cores

Docker Stack
```

version: '2'

services:
  wekandb:
     image: mongo:4.4
    #-------------------------------------------------------------------------------------
     container_name: wekan-db
     restart: always
     command: mongod --logpath /dev/null --oplogSize 128 --quiet
     networks:
      - wekan-tier
     expose:
      - 27017
     volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump
  wekan:
    image: quay.io/wekan/wekan
    #-------------------------------------------------------------------------------------
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    #-------------------------------------------------------------------------------------
    ports:
      - 13001:8080
    environment:
      #-----------------------------------------------------------------
      # ==== WRITEABLE PATH FOR FILE UPLOADS ====
      - WRITABLE_PATH=/data
      #-----------------------------------------------------------------
      # ==== MONGO_URL ====
      - MONGO_URL=mongodb://wekandb:27017/wekan
      #---------------------------------------------------------------
      - ROOT_URL=http://domain.tld/wekan  #   <=== using only at same laptop/desktop where Wekan is installed
      #---------------------------------------------------------------
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      #---------------------------------------------------------------
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      #-----------------------------------------------------------------
      # ==== AUTHENTICATION
      - DEFAULT_AUTHENTICATION_METHOD=ldap
      - PASSWORD_LOGIN_ENABLED=true
      #-----------------------------------------------------------------
      # ==== LDAP BASEDN Auth ====
      - LDAP_ENABLE=true
      - LDAP_PORT=389
      - LDAP_HOST=DC.domain.tld
      - LDAP_BASEDN=dc=domain,dc=tld
      - LDAP_LOGIN_FALLBACK=false
      - LDAP_RECONNECT=true
      - LDAP_TIMEOUT=10000
      - LDAP_IDLE_TIMEOUT=10000
      - LDAP_CONNECT_TIMEOUT=10000
      - LDAP_AUTHENTIFICATION=true
      - LDAP_AUTHENTIFICATION_USERDN=uid=ldaplogin,cn=users,dc=domain,dc=tld
      - LDAP_AUTHENTIFICATION_PASSWORD=
      - LDAP_LOG_ENABLED=true
      - LDAP_BACKGROUND_SYNC=true
      - LDAP_BACKGROUND_SYNC_INTERVAL=100
      - LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=false
      - LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=true 
      - LDAP_REJECT_UNAUTHORIZED=false
      - LDAP_USER_SEARCH_FILTER=(|(memberof=cn=grp-wekan,cn=groups,dc=domain,dc=tld))
      - LDAP_USER_SEARCH_SCOPE=sub
      - LDAP_USER_SEARCH_FIELD=uid
      - LDAP_SEARCH_PAGE_SIZE=0
      - LDAP_SEARCH_SIZE_LIMIT=0
      - LDAP_GROUP_FILTER_ENABLE=true
      - LDAP_GROUP_FILTER_OBJECTCLASS=
      - LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE=
      - LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE=uniqueMember
      - LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT=dn
      - LDAP_GROUP_FILTER_GROUP_NAME=
      - LDAP_UNIQUE_IDENTIFIER_FIELD=uidNumber
      - LDAP_UTF8_NAMES_SLUGIFY=true
      - LDAP_USERNAME_FIELD=uid
      - LDAP_FULLNAME_FIELD=displayName
      - LDAP_MERGE_EXISTING_USERS=false
      - LDAP_EMAIL_FIELD=mailPrimaryAddress
      - LDAP_SYNC_USER_DATA_FIELDMAP={"cn":"name", "mailPrimaryAddress":"email"}
      - LDAP_DEFAULT_DOMAIN=domain.tld
      - LDAP_SYNC_ADMIN_STATUS=true
      - LDAP_SYNC_ADMIN_GROUPS=
      - LDAP_BASE=dc=domain,dc=tld
      - LDAP_SERVER_IP=
      - LDAP_SERVER_NAME=central.domain.tld
      - LDAP_SERVER_PORT=389
      - LDAP_SERVER_TYPE=master
      - LDAP_MASTER=central.domain.tld
      - LDAP_MASTER_PORT=389
      - LOCALE=en_US.UTF-8:UTF-8 de_DE.UTF-8:UTF-8
      - LOCALE_DEFAULT=de_DE.UTF-8:UTF-8
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw


volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
```

### Problem description
Covers not visible

#### Reproduction Steps
Upload a Cover
On the Card the Cover is not visible
![2022-06-01 08_38_54-C-lab Notizen und Nützliches -](https://user-images.githubusercontent.com/21257329/171343278-d584c1d8-11d1-4709-ab28-a33317b82780.jpg)

#### Logs
In the Docker logs is nothing while upload the image

Firefox Console:
On the DNS Domain Web adress i get the Same Errors
![grafik](https://user-images.githubusercontent.com/21257329/171344941-0a0a386a-4a1b-4576-a724-78bf26b1cffc.png)
