### ISSUE TITLE
Wekan installation guide

### ISSUE THREAD

**Issue by g-giordano** [wekan/wekan#4566]
I want install wekan 6.28 and wekan-gant  via snap on ubuntu 21, but I install only wekan old version.
I have tried to install with docker but whe I try to connect at th root url he doesn't show any pages, any idea?
Have you a guide step by step?
TKS
best regards

**Comment by DimDz** [comment]
This is how I did it with docker.

- git clone https://github.com/wekan/wekan.git
- edit **_ROOT_URL_** on _**docker-compose.yml**_ with your ip
- cd wekan
- docker-compose up -d

if you want to build from source just uncomment this
```
   # build:
   #   context: .
   #   dockerfile: Dockerfile
```
and use **_docker-compose up -d --build_** instead of **_docker-compose up -d_**

**Comment by xet7** [comment]
@g-giordano 

I added some more links to Snap install page:
https://github.com/wekan/wekan-snap/wiki/Install

**Comment by g-giordano** [comment]
Hi Lauri,
I installed wekan via snap, on ubuntu server 20.04.3 LTS operating system
(GNU / Linux 5.4.0-120-generic x86_64) , is installed  an obsolete version
of wekan 6.0.9 (screenshoot -1) not 6.28, also missing the menu " Archive
"(screenshot-2), how can I install version 6.28 with gant and menu 'archive?
Thank you

Il giorno mer 22 giu 2022 alle ore 18:28 Lauri Ojansivu <
***@***.***> ha scritto:

**Comment by g-giordano** [comment]
Hi,
I have installed wekan with docker installation guide, but doesn't start
,if I connect to the http://myip:8080 wekan don't show, I see in my docker
container mongo 5 it restarts continuously.
Any idea?

Il giorno mer 22 giu 2022 alle ore 10:33 DimDz ***@***.***>
ha scritto:

**Comment by g-giordano** [comment]
Help me please!!

**Comment by xet7** [comment]
@g-giordano 

What does this command output on your server?

free -h

**Comment by g-giordano** [comment]
Hi xet7, an attached output command.
TKs
![free-h](https://user-images.githubusercontent.com/73339237/176991660-df24a9aa-bf6a-4635-b6b3-da6a13e9ded3.png)

**Comment by g-giordano** [comment]
ho @xet7. can giù help me?
ros
Giuseppe

**Comment by CActor** [comment]
Hi guys.
I have the same problem. Does anyone have a solution ? 
Gabriele

**Comment by zz707** [comment]
Hi, I just copy the default file docker-compose.yml and run docker-compose and get this error
```javascript
ReferenceError: userInfo is not defined
wekan_1      |     at module (server/00checkStartup.js:13:32)
wekan_1      |     at fileEvaluate (packages/modules-runtime.js:336:7)
wekan_1      |     at Module.require (packages/modules-runtime.js:238:14)
wekan_1      |     at require (packages/modules-runtime.js:258:21)
wekan_1      |     at /build/programs/server/app/app.js:162577:1
wekan_1      |     at /build/programs/server/boot.js:401:38
wekan_1      |     at Array.forEach (<anonymous>)
wekan_1      |     at /build/programs/server/boot.js:226:21
wekan_1      |     at /build/programs/server/boot.js:464:7
wekan_1      |     at Function.run (/build/programs/server/profile.js:280:14)
wekan_1      |     at /build/programs/server/boot.js:463:13
wekan_1      | /build/programs/server/node_modules/fibers/future.js:280
wekan_1      |                                          throw(ex);
```

**Comment by mfilser** [comment]
@zz707 
I can have a look at this

**Comment by mfilser** [comment]
I have an idea about the missing code but don't have access to my development environment right now. 
Anyway, the code is reached because of another configuration error. The WRITABLE_PATH can't be changed of the user which is used for wekan.

**Comment by zz707** [comment]
> @zz707 I can have a look at this

```yaml
version: '2'

services:

  wekandb:
    image: mongo:5.0
    container_name: wekan-db
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
      - ./dump:/dump

  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: unless-stopped
    volumes:
      - ./data/wekan-files:/data
    ports:
      - 8011:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://wekan.loc:8011  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - CORS=*
      - CORS_ALLOW_HEADERS=Authorization,Content-Type
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
  ```
