### ISSUE TITLE
Request to site.webmanifest does not send credentials

### ISSUE THREAD

**Issue by markormesher** [wekan/wekan#4800]
### Server Setup Information

* Did you test in newest Wekan?: Yes, v.6.67
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Debian
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker image running in Kubernetes
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik
* Node.js Version: N/A (whatever is used in the Docker image)
* MongoDB Version: 4.4.18
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Chrome 108

### Problem description

All pages of Wekan include a `<link rel="manifest"/>` to `/site.webmanifest` in the header. These requests do not include authorisation headers, causing them to fail (when using Authelia at least - other auth providers may differ). This is a "feature" of manifest links, as described at https://github.com/w3c/manifest/issues/535#issuecomment-435739223, and is resolved by explicitly instructing the browser to include credentials on that request.

#### Reproduction Steps

- Configure Wekan to use Authelia as an OIDC auth provider (likely reproducible with other providers too)
- Open any Wekan page and check for failing requests

#### Logs

N/A

#### Config

Auth setup for reference:

<details>
<summary>Authelia config</summary>

```yaml
identity_providers:
  oidc:
    clients:
      - id: wekan
        description: Wekan
        secret: "redacted"
        redirect_uris:
          - https://wekan.my.domain/_oauth/oidc
        scopes:
          - openid
          - email
          - profile
```
</details>

<details>
<summary>Wekan environment variables</summary>

```yaml
  - name: OIDC_REDIRECTION_ENABLED
    value: "true"
  - name: OAUTH2_ENABLED
    value: "true"
  - name: OAUTH2_LOGIN_STYLE
    value: redirect
  - name: OAUTH2_CLIENT_ID
    value: wekan
  - name: OAUTH2_SECRET
    value: "redacted"
  - name: OAUTH2_SERVER_URL
    value: https://auth.my.domain
  - name: OAUTH2_AUTH_ENDPOINT
    value: /api/oidc/authorization
  - name: OAUTH2_USERINFO_ENDPOINT
    value: /api/oidc/userinfo
  - name: OAUTH2_TOKEN_ENDPOINT
    value: /api/oidc/token
  - name: OAUTH2_ID_MAP
    value: email
  - name: OAUTH2_USERNAME_MAP
    value: preferred_username
  - name: OAUTH2_FULLNAME_MAP
    value: name
  - name: OAUTH2_EMAIL_MAP
   value: email
```
</details>
