### ISSUE TITLE
sharedDataFolder persisdent provide by k8s has no permission to mkdir and write

### ISSUE THREAD

**Issue by lihongbo138** [wekan/wekan#4921]
### Server Setup Information

* Did you test in newest Wekan?:
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* Operating System:
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version:
* MongoDB Version:
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?

**Comment by lihongbo138** [comment]
I deployed wekan in k8s with k8s-ceph-storage.  the wekan container failed with exception of no permission to mkdir under /data.
any other app deployed in k8s with ceph-storage class is ok.   i don't knwn why the user[wekan] that run wekan may not have permission.  so i have to disable shared datafolder,and it can work.
config as follw:
sharedDataFolder:
  enabled: true
  path: /data
  accessMode: ReadWriteMany
  storageClass: rook-cephfs
  resources:
    requests:
      storage: 5Gi

**Comment by xet7** [comment]
@Nightreaver

Do you know how to fix this?

Related https://github.com/wekan/charts/issues/14

**Comment by lihongbo138** [comment]
I didn't try to fix it. 
 "ls  -al  /" in a container without sharedatafolder. "/data" owner is wekan and group is root. please check if init script runner has permission to make subdir in '/data'

**Comment by Nightreaver** [comment]
Are you running multiple pods? Otherwise you might just try ReadWriteOnce which might have different permissions. Otherwise, you might add an init-container for fixing permissions, I don't think here is one currently

**Comment by new2001y** [comment]
need chart template edit.
add initContainer.

1. `helm pull wekan/wekan --untar`
2. `cd wekan/`
3. edit templates/deployment.yaml
```
spec:
  template:
    ...
    spec:
      serviceAccountName: {{ template "wekan.serviceAccountName" . }}
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 999:999 /data']
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data
      containers:
        ...
```
4. helm install wekan . -f values.yaml
