### ISSUE TITLE
[Docker] /data is not writable

### ISSUE THREAD

**Issue by knacky34** [wekan/wekan#5164]
### Server Setup Information
* Did you test in newest Wekan?: **Yes, version 7.10 (docker image wekanteam/wekan:latest)**
* Did you configure root-url correctly so Wekan cards open correctly? **Yes**
* Operating System: **VM Debian 12**
* Deployment Method: **Docker (podman)**
* Http frontend: **Caddy**
* Node.js Version: **bundled in docker image**
* MongoDB Version: **bundled in docker image**

### Problem description
Directory `/data` in the container belongs to  `root` instead of `wekan` user. This prevent Wekan from starting properly as it can't write attachments. I saw that by entering the container and `ls -l /`
What is wierd though, is that in [Dockerfile](https://github.com/wekan/wekan/blob/main/Dockerfile#L258) user wekan is set correctly.
I tried running the container both with and without WRITABLE_PATH env.

Here is the commands used to setup the container:
```
sudo mkdir -p /var/lib/wekan/data

sudo podman run -d \
    -e ROOT_URL=https://boards.nas.local \
    -e MONGO_URL=mongodb://wekan:wekanpass@mongo:27017/wekan?authSource=admin \
    -e WRITABLE_PATH=/data \
    -e MAIL_URL=smtp://localhost \
    -e MAIL_FROM="Wekan Notifications <noreply.wekan@boards.nas.local>" \
    -v /var/lib/wekan/data:/data \
    --net backend_tier \
    --name wekan docker.io/wekanteam/wekan:latest
```

#### Logs
```
/build/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
errorClass [Error]: [FilesCollection.attachments] Path "/data/attachments" is not writable! [401]
    at new FilesCollection (packages/ostrio:files/server.js:356:15)
    at module (models/attachments.js:49:15)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/build/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (server/publications/attachments.js:1:24)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /build/programs/server/app/app.js:189159:1
    at /build/programs/server/boot.js:385:38
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:210:21
    at /build/programs/server/boot.js:439:7
    at Function.run (/build/programs/server/profile.js:256:14)
    at /build/programs/server/boot.js:438:13 {
  isClientSafe: true,
  error: 401,
  reason: '[FilesCollection.attachments] Path "/data/attachments" is not writable!',
  details: Error: EACCES: permission denied, mkdir '/data/attachments'
      at Object.mkdirSync (fs.js:1014:3)
      at new FilesCollection (packages/ostrio:files/server.js:350:10)
      at module (models/attachments.js:49:15)
      at fileEvaluate (packages/modules-runtime.js:336:7)
      at Module.require (packages/modules-runtime.js:238:14)
      at Module.moduleLink [as link] (/build/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
      at module (server/publications/attachments.js:1:24)
      at fileEvaluate (packages/modules-runtime.js:336:7)
      at Module.require (packages/modules-runtime.js:238:14)
      at require (packages/modules-runtime.js:258:21)
      at /build/programs/server/app/app.js:189159:1
      at /build/programs/server/boot.js:385:38
      at Array.forEach (<anonymous>)
      at /build/programs/server/boot.js:210:21
      at /build/programs/server/boot.js:439:7
      at Function.run (/build/programs/server/profile.js:256:14)
      at /build/programs/server/boot.js:438:13 {
    errno: -13,
    syscall: 'mkdir',
    code: 'EACCES',
    path: '/data/attachments'
  },
  errorType: 'Meteor.Error'
}
```

**Comment by xet7** [comment]
@knacky34 

Hmm. Are you not using newest docker-compose.yml from https://github.com/wekan/wekan or Kubernetes Helm Chart from link at https://wekan.github.io ? Those should set /data properly.

**Comment by knacky34** [comment]
@xet7, no I created my own script to deploy the containers. I'm sure the issue is not related to mongo as Wekan succesfully created some collections in mongodb.
But I use container image provided by this repo and I just don't understand why the `chown wekan -R /data` didn't do the job in Dockerfile.
However, I will try using the compose file provided and using docker instead of podman.

**Comment by xet7** [comment]
@knacky34 

```
chown -R 999:999 /data
```
https://github.com/wekan/charts/pull/21/files

**Comment by knacky34** [comment]
@xet7
`chown 999` didn't help but I managed to fix the issue.
The reason why the user of `/data` was still `root` is because I used mountpoints and not managed volumes. This caused the permission to be reset.

I fixed the issue using managed volumes. ([see Stackoverflow post](https://stackoverflow.com/a/39398511/11251801)).
Finally, I simply fixed the issue using `chown -R 999:999 /path/to/data/on/host`

**Comment by devopser-test** [comment]
I didnt want to use the docker-volume so ive com up with this solution:
in the docker compose (i updated to version 3.9)

```yml
version: '3.9'


services:

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/data/wekan/db:/data/db
      - /docker/data/wekan/db-dump:/dump

  init-wekan:
    image: busybox
    container_name: init-wekan
    volumes:
      - /docker/data/wekan/data:/data:rw
    command: chown -R 999:999 /data

  wekan:
    image: ghcr.io/wekan/wekan:v7.30
    container_name: wekan
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - WRITABLE_PATH=/data

    depends_on:
      wekandb:
        condition: service_started
      init-wekan:
        condition: service_completed_successfully

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/data/wekan/data:/data:rw


```
