### ISSUE TITLE
Is nginx really forwarding?

### ISSUE THREAD

**Issue by vitello** [wekan/wekan#526]
I have installed everything as described in **Install Wekan Docker in production** and everything runs perfectly on my ubuntu server, except that I have to directly enter the URL **INCLUDING** the Port, like http://192.168.x.x:8081 from my service-pc. I guessed that nginx is not forwarding the Port-80-Requests and indeed, when I stopped the nginx-service, the wekan-app is **still** reachable with the same URL.
What is the problem?

**Comment by Asara** [comment]
server {
        server_name wallabag.domain.com;
        listen 80;
        location / {
            proxy_pass http://10.1.1.13:8000;
            proxy_set_header        Referer                 $http_referer;
            proxy_set_header Host "$host";
            proxy_pass_request_headers      on;
        }


Works with nginx 1.8.0 for me.  Give it a try?

**Comment by vitello** [comment]
No chance. It doesn't work with **http://x.x.x.x/sign-in**, it always requires **http://x.x.x.x:8081/sign-in**.
My /home/XXX/wekan/docker-compose.yml:
```
wekan:
  image: mquandalle/wekan
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://127.0.0.1:8081
  ports:
    - 8081:80

wekandb:
   image: mongo
   volumes:
     - /home/XXX/wekan/data:/data/db
```
And my /etc/nginx/sites-available/wekan.conf:
```
server {
    server_name XXX.de;
    listen 80;
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Referer $http_referer;
        proxy_set_header Host "$host";
        proxy_pass_request_headers on;
    }
}
```
Do find an error?
