### ISSUE TITLE
Missing translations and site not loading properly

### ISSUE THREAD

**Issue by topezno** [wekan/wekan#5280]
## Issue
I'm having the same problem as [https://github.com/wekan/wekan/issues/4797](https://github.com/wekan/wekan/issues/4797) with the docker version: only placeholders are shown instead of translations, uploaded pictures aren't shown, and the whole site seems not to load completely.
I've checked the former and other issues, like [https://github.com/wekan/wekan/issues/4803](https://github.com/wekan/wekan/issues/4803) and ROOT_URL seems properly set in docker-compose.yml. 
Below are the only changes I made to the original compose file:
``` 
 wekan:
   image: wekanteam/wekan:latest` 
 ports: 
    - 3003:8080 
 environment: 
    - ROOT_URL=http://10.116.245.254  
``` 
I've checked the browsers' (chrome and firefox latest versions) devtools console and there seems to be problems with CORS:
![image](https://github.com/wekan/wekan/assets/158448624/16c7d674-daf9-4f2f-b6bb-ce2008fb9812)
I don't know if this is related with the problem.

I'm accesing with a computer within the same local network.
Server OS: Ubuntu server 22.04.3
