### ISSUE TITLE
LDAP users and groups not syncing

### ISSUE THREAD

**Issue by nixoletas** [wekan/wekan#5361]
## LDAP Users groups not showing, import accounts

i was able to use LDAP for authentication, but, accounts are only created after login. Is there a way to auto import users from LDAP, so i can start assigning them to boards? I'm also not being able to display the users already assinged groups. When i log in, it shows no groups.

i used docker inside a Proxmox LXC container and the latest wekan and mongo images, also the docker-compose.yml and i also tried to mess with LDAP template compose file but had no success.

```yaml
version: '2'
services:
  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump
  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 80:8080
    environment:
      - lng=pt_BR
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://10.56.19.140
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - DEFAULT_AUTHENTICATION_METHOD=ldap
      - LDAP_ENABLE=true
      - LDAP_PORT=389
      - LDAP_HOST=10.56.19.130
      - LDAP_DEFAULT_DOMAIN=ldap.example.com.br
      - LDAP_BASEDN=DC=example,DC=com,DC=br
      - LDAP_LOGIN_FALLBACK=false
      - LDAP_RECONNECT=true
      - LDAP_AUTHENTIFICATION=true
      - LDAP_AUTHENTIFICATION_USERDN=CN=admin,OU=Usuarios,OU=exampler,DC=example,DC=com,DC=br
      - LDAP_AUTHENTIFICATION_PASSWORD=mypassword
      - LDAP_LOG_ENABLED=true
      - LDAP_BACKGROUND_SYNC=true
      - LDAP_BACKGROUND_SYNC_INTERVAL='every 1 hour'
      - LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=true
      - LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=true
      - LDAP_ENCRYPTION=false
      - LDAP_REJECT_UNAUTHORIZED=false
      - LDAP_USER_SEARCH_FILTER=
      - LDAP_USER_SEARCH_SCOPE=
      - LDAP_USER_SEARCH_FIELD=sAMAccountName
      - LDAP_SEARCH_PAGE_SIZE=
      - LDAP_SEARCH_SIZE_LIMIT=
      - LDAP_GROUP_FILTER_ENABLE=true
      - LDAP_GROUP_FILTER_OBJECTCLASS=group
      - LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE=
      - LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE=
      - LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT=
      - LDAP_GROUP_FILTER_GROUP_NAME=
      - LDAP_UNIQUE_IDENTIFIER_FIELD=
      - LDAP_UTF8_NAMES_SLUGIFY=true
      - LDAP_USERNAME_FIELD=cn
      - LDAP_MERGE_EXISTING_USERS=true
      - LDAP_SYNC_USER_DATA=true
      - LDAP_SYNC_GROUP_ROLES=''
      - LDAP_DEFAULT_DOMAIN=example.com.br
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw
volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge

``` 

i just don't know how to use all of these group params and how to find LDAP corresponding field
