### ISSUE TITLE
Cannot save Layout settings

### ISSUE THREAD

**Issue by tensor5g** [wekan/wekan#5630]
### Server Setup Information

Docker on Ubuntu 22.04: ghcr.io/wekan/wekan:latest

### Problem description

I cannot edit Settings/Layout, I get an error in my browser's console:

![image](https://github.com/user-attachments/assets/7ade580b-0e26-45a5-9960-eb3a67cf6fb1)

![image](https://github.com/user-attachments/assets/9fbae3b9-ac82-4c2f-9c57-2279bd91fece)

It appears the object it's trying to reference "accessibility-title" and "accessibility-content" do not exist on my settings page. 
This is a practically brand new instance, I have not used wekan before, so I don't know if this problem is new. 
Tested in Firefox and Edge.

#### Reproduction Steps
Open layout menu under admin panel and try to save it with or without changing any settings. 
Error will appear in console and loading symbol will appear endlessly.
I've tested this immediately after a deleting all volumes and starting fresh with this docker compose:
```yaml
services:
  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 3001:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://192.168.100.100:3001 
      - MAIL_URL=smtp://smtp.example.com:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM="Wekan <wekan@example.com>"
      - WITH_API=false
      - RICHER_CARD_COMMENT_EDITOR=true
      - CARD_OPENED_WEBHOOK_ENABLED=false
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump

volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
```

#### Logs

There are no errors in my container's logs (Just one line about SyncedCron). Edge logs above.
