### ISSUE TITLE
Disable sign up

### ISSUE THREAD

**Issue by max21** [wekan/wekan#569]
Hi,
It is possible to turn off sign up ?

Thanks :)

**Comment by martingabelmann** [comment]
You can disable signups by modifying the  [wekan/config/accounts.js](https://github.com/wekan/wekan/blob/90428e7ba1c0e4185f92dc26b793aff1a9e04bc6/config/accounts.js)

On [L17](https://github.com/wekan/wekan/blob/90428e7ba1c0e4185f92dc26b793aff1a9e04bc6/config/accounts.js#17) add
```
forbidClientAccountCreation: true,
```
and on  [Line 28](https://github.com/wekan/wekan/blob/90428e7ba1c0e4185f92dc26b793aff1a9e04bc6/config/accounts.js#27) remove the ``signUp,``.

**Comment by jbvioix** [comment]
Hi,
I'm using docker and I have two accounts.js in my container : 
- /app/config/accounts.js
- /built_app/programs/server/app/config/accounts.js
Which one I have to change to disable sign up?
Thanks,

**Comment by martingabelmann** [comment]
the second one worked for me:  
``/built_app/programs/server/app/config/accounts.js``

btw. heres my docker-compose for this setup:

```
wekan:
  image: mquandalle/wekan
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=https://your.fqdn.com
  volumes:
    - /srv/docker/wekan/config:/built_app/programs/server/app/config

wekandb:
   image: mongo
   volumes:
     - /srv/docker/wekan/db:/data/db
```

the account.js is located at ``/srv/docker/wekan/config``.
