### ISSUE TITLE
Add support for Docker/Compose Secrets for passwords

### ISSUE THREAD

**Issue by Roemer** [wekan/wekan#5724]
Secrets can be used in Docker/Compose in order to not have passwords floating around as environment variables.
This is especially usefull for passwords (and possibly user-names or other sensitive data as well).

In a compose file, this usually looks like (only relevant parts:
```yaml
services:
  db:
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password

  app:
    environment:
      - FILE__DB_PASS=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - db

secrets:
   db_password:
     file: db_password.txt
```

The idea behind the secrets is that they are a simple text file containing the password as text and those are mounted into `/run/secrets/...`. The environment variables that are suffixed with `_FILE` (in some cases also prefixed like the linuxserver images). With that identifier, the Docker image knows that it needs to read the variable from this file instead of just using it as a text variable.

This makes it more secure as one needs file-access to the container (or host) to get the password. Having them in the environment variables is insecure as it is often possible in the application to output the environment variables in one way or another.

So please add a `_FILE` variant for the relevant environment variables.
