### ISSUE TITLE
Use the Docker run the wekan, but only a blank page.

### ISSUE THREAD

**Issue by izuolan** [wekan/wekan#712]
My docker-compose.yml

```
version: '2'
services:
  wekan:
    image: mquandalle/wekan
    ports:
      - "4080:80"
    links:
      - wekandb
    environment:
      - MONGO_URL=mongodb://wekandb/wekan
      - ROOT_URL=http://172.16.168.168:4080
  wekandb:
    image: library/mongo
    volumes:
      - ./data:/data/db
```

The log:

```
➜  wekan docker-compose up   
Creating wekan_wekandb_1
Creating wekan_wekan_1
Attaching to wekan_wekandb_1, wekan_wekan_1
wekandb_1  | 2016-10-17T06:45:02.270+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=44e114dac6fd
wekandb_1  | 2016-10-17T06:45:02.271+0000 I CONTROL  [initandlisten] db version v3.2.10
wekandb_1  | 2016-10-17T06:45:02.271+0000 I CONTROL  [initandlisten] git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
wekandb_1  | 2016-10-17T06:45:02.271+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
... ...
... ...
wekandb_1  | 2016-10-17T06:45:07.430+0000 I INDEX    [conn3]     building index using bulk method
wekandb_1  | 2016-10-17T06:45:07.431+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
wekandb_1  | 2016-10-17T06:45:07.447+0000 I INDEX    [conn6] build index on: wekan.cards properties: { v: 1, key: { boardId: 1 }, name: "boardId_1", ns: "wekan.cards" }
wekandb_1  | 2016-10-17T06:45:07.447+0000 I INDEX    [conn6]     building index using bulk method
wekandb_1  | 2016-10-17T06:45:07.448+0000 I INDEX    [conn6] build index done.  scanned 0 total records. 0 secs
wekandb_1  | 2016-10-17T06:45:07.461+0000 I INDEX    [conn4] build index on: wekan.lists properties: { v: 1, key: { boardId: 1 }, name: "boardId_1", ns: "wekan.lists" }
wekandb_1  | 2016-10-17T06:45:07.462+0000 I INDEX    [conn4]     building index using bulk method
wekandb_1  | 2016-10-17T06:45:07.463+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
```

This seems to be run successfully， but I only see a blank page. No error.
How can I fix ?
