### ISSUE TITLE
Wiki: Update install instructions for docker-compose

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [wekan/wekan#752]
I am following the [instructions from the wiki](https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing) to get Wekan running with Docker.

Problem is, the given config file `docker-compose.yml` is written in [version 1](https://docs.docker.com/compose/compose-file/#/versioning) of the docker-compose specification, which is soon going to be deprecated.

I am going to update the first example to version 2 following [this guide](https://docs.docker.com/compose/compose-file/#upgrading). 

There is also a [second page](https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production) with instructions, but I can not upgrade these since I could not get the example working in the first place.

**Comment by centigrade-thomas-becker** [comment]
The new `docker-compose.yml` would be:

```
version: '2'
services:
  wekan:
    image: mquandalle/wekan
    links:
      - wekandb
    environment:
      - MONGO_URL=mongodb://wekandb/wekan
      - ROOT_URL=http://localhost:80
    ports:
      - 80:80

  wekandb:
    image: mongo
    volumes:
      - /home/johndoe/wekan/data:/data/db
```

When I create the container with `docker-composer up -d` I get a working Wekan with MongoDB.
