### ISSUE TITLE
[Mail] TLS/SSL issue

### ISSUE THREAD

**Issue by n00b42** [wekan/wekan#989]
I tried to set my SMTP server both via config and via admin panel, but wekan still can not send mails.

```
wekan:
  image: wekanteam/wekan:meteor-1.4
  restart: always
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://wekan.mydomain.de
    #- MAIL_URL=smtp://robot@mydomain.de:SOMEPASSWORD@mail.mydomain.de:587/
    - MAIL_FROM=robot@mydomain.de
  ports:
    - 9201:80

wekandb:
  image: mongo
  restart: always
  volumes:
    - /home/wekan/data:/data/db
```

Error

```Error: 140372779964192:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:```

Furthermore, it prints another error:

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
```

**It may be related to my SMTP server not accepting SSLv3 connections (security reasons)?**
